name: Biddist_CI
on:
  push:
    branches:
      - '**'
jobs:
  build_backend:
    env:
      MAILGUN: ${{secrets.MAILGUN}}
      MAILGUN_DOMAIN: ${{secrets.MAILGUN_DOMAIN}}
      FRONTEND_DOMAIN: ${{secrets.FRONTEND_DOMAIN}}
      STRIPE: ${{secrets.STRIPE}}
      DB_CONN: ${{secrets.DB_CONN}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [latest, lts-bookworm-slim lts-bullseye-slim]
        shard: [1, 2]
    container: node:${{matrix.node}}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        working-directory: ./biddist_backend
      - run: npm test --shard=${{matrix.shard}}/2
        working-directory: ./biddist_backend
      - run: npm run build --if-present
        working-directory: ./biddist_backend
  build_frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [latest, lts-bookworm-slim, lts-bullseye-slim]
    container: node:${{matrix.node}}
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
        working-directory: ./biddist_frontend
      - run: npm test
        working-directory: ./biddist_frontend
      - run: npm run build --if-present
        working-directory: ./biddist_frontend
