name: Biddist_CI
on: [push]
jobs:
  build_backend:
    env:
      work_dir: ./biddist_backend
      MAILGUN: ${{secrets.MAILGUN}}
      MAILGUN_DOMAIN: ${{secrets.MAILGUN_DOMAIN}}
      FRONTEND_DOMAIN: ${{secrets.FRONTEND_DOMAIN}}
      STRIPE: ${{secrets.STRIPE}}
      DB_CONN: ${{secrets.DB_CONN}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18, 20, 23]
        shard: [1, 2, 3]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: npm ci
        working-directory: ${{env.work_dir}}
      - run: npm test --shard=${{matrix.shard}}/3
        working-directory: ${{env.work_dir}}
      - run: npm run build --if-present
        working-directory: ${{env.work_dir}}
  build_frontend:
    env:
      work_dir: ./biddist_frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ 16, 18 , 20, 23 ]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: npm ci
        working-directory: ${{env.work_dir}}
      - run: npm test
        working-directory: ${{env.work_dir}}
      - run: npm run build --if-present
        working-directory: ${{env.work_dir}}
