name: Biddist_CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16, 18 , 20, 23]
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node}}
      - run: cd biddist_backend && npm ci
      - run: cd biddist_backend && npm test
      - run: cd biddist_backend && npm run build --if-present
