name: Biddist_CI
on: [push]
jobs:
  build_backend:
    env:
      MAILGUN: ${{secrets.MAILGUN}}
      MAILGUN_DOMAIN: ${{secrets.MAILGUN_DOMAIN}}
      FRONTEND_DOMAIN: ${{secrets.FRONTEND_DOMAIN}}
      STRIPE: ${{secrets.STRIPE}}
      DB_CONN: ${{secrets.DB_CONN}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [node:latest, node:lts-bookworm-slim, node:lts-bullseye-slim]
        shard: [1, 2]
    container: ${{matrix.node}}
    steps:
      - run: npm ci
        working-directory: ./biddist_backend
      - run: npm test --shard=${{matrix.shard}}/2
        working-directory: ./biddist_backend
      - run: npm run build --if-present
        working-directory: ./biddist_backend
  build_frontend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [node:latest, node:lts-bookworm-slim, node:lts-bullseye-slim]
    container: ${{matrix.node}}
    steps:
      - run: npm ci
        working-directory: ./biddist_frontend
      - run: npm test
        working-directory: ./biddist_frontend
      - run: npm run build --if-present
        working-directory: ./biddist_frontend
