name: deploy.yml
on:
  push:
    branches:
      - 'main'
jobs:
  aws_upload:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    name: aws_upload
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        name: get_credentials
        with:
          aws-region: 'us-east-2'
          role-to-assume: ${{secrets.AWS_ROLE}}
      - name: terraform_setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 'latest'
          terraform_wrapper: 'false'
      - name: terraform_init
        run: terraform init
      - name: terraform_plan
        run: terraform plan -input=false
      - name: terraform_apply
        run: terraform apply -auto-approve -input=false
      - name: build_javascript
        run: |
          cd biddist_backend
          npm ci
          npm run build
          cd ../biddist_frontend
          npm ci
          npm run build
      - name: production_test
        working-directory: ./biddist_backend
        run: npm run production_test
      - name: build_and_push_image
        working-directory: .
        run: |
          url=$(terraform output -raw ecr_url)
          docker build -t biddist/backend:latest -t $url ./biddist_backend
          docker push $url
      - name: sync_backend_files
        working-directory: ./biddist_backend
        run: |
          aws s3 sync dist s3://biddist-backend --delete
      - name: sync_frontend_files
        working-directory: ./biddist_frontend
        run:
          aws s3 sync dist s3://biddist-frontend --delete
